wordpress:
  image: wordpress
  links:
    - mariadb:mysql
  environment:
    - WORDPRESS_DB_PASSWORD=secret
    - WORDPRESS_DB_USER=root
  ports:
    - 80:80
  volumes:
    - ./html:/var/www/html:cached
mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=wordpress
  volumes:
    - ./database:/var/lib/mysql

reverse-proxy:
  image: "nginx:latest"
  volumes:
    - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "8080:88"
